import Link from "next/link";

export const metadata = {
  title: "about",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <div className=" pt-16 ">
        <div className=" flex items-center gap-6 ">
            <Link href={"/about/mission"}>Mission</Link>
            <Link href={"/about/vission"}>Vission</Link>
        </div>
        {children}
    </div>
   
  );
}
