import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${inter.className} bg-[#000] min-h-[100vh] text-[#fff] p-40 `}>
        
        <div className=" flex items-center gap-7 ">
          <Link href={'/'}>Home</Link>
          <Link href={"/about"}>About</Link>
          <Link href={"/portfolio"}>Portfolio</Link>
          <Link href={"/blogs"}>Blogs</Link>
          <Link href={"/contact"}>Contact</Link>
          <Link href={"/posts"}>Posts</Link>
        </div>

        {children}
        
        </body>
    </html>
  );
}
